# Generated by Django 4.0.3 on 2022-06-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0001_initial'),
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_program',
            field=models.ManyToManyField(blank=True, to='eduprogramsapp.eduprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_limitations',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='studentsapp.healthlimitations'),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_status',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='studentsapp.socialstatus'),
        ),
    ]
