# Generated by Django 4.0.3 on 2022-07-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0002_rename_adapted_eduprogram_is_adapted_and_more'),
        ('studentsapp', '0002_alter_student_edu_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_program',
            field=models.ManyToManyField(to='eduprogramsapp.eduprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_limitations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='studentsapp.healthlimitations'),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='studentsapp.socialstatus'),
        ),
    ]
