# Generated by Django 4.0.3 on 2022-07-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneruser',
            name='position',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='authapp.positionpioneruser', verbose_name='Должность'),
        ),
    ]
