# Generated by Django 4.0.3 on 2022-07-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_pioneruser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pioneruser',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='authapp.positionpioneruser', verbose_name='Должность'),
        ),
    ]
