# Generated by Django 4.0.3 on 2022-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_pioneruser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionpioneruser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Редактирование журнала учёта занятий'),
        ),
    ]
