# Generated by Django 4.0.3 on 2022-06-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapted', models.BooleanField(default=False, verbose_name='Адаптированность')),
                ('duration', models.IntegerField(default=8, verbose_name='Продолжительность, ч')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('orientation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='eduprogramsapp.orientationprogram')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='eduprogramsapp.typeprogram')),
            ],
        ),
    ]
