# Generated by Django 4.0.3 on 2022-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduprogram',
            old_name='adapted',
            new_name='is_adapted',
        ),
        migrations.AlterField(
            model_name='orientationprogram',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Направленность'),
        ),
    ]
