# Generated by Django 4.0.3 on 2022-07-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0003_alter_eduprogram_orientation_alter_eduprogram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Наименование'),
        ),
    ]
