# Generated by Django 4.0.3 on 2022-08-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0005_eduprogram_program_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=8, verbose_name='Продолжительность, ч')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('edu_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprogramsapp.eduprogram', verbose_name='Основная программа')),
            ],
        ),
    ]
