# Generated by Django 4.0.3 on 2022-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0006_workprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprogram',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
    ]
