# Generated by Django 4.0.3 on 2022-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprogramsapp', '0007_alter_workprogram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprogram',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность, ч'),
        ),
    ]
